name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  security:
    name: Security Scan (Semgrep, OWASP ZAP, Trivy)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Create Docker network for testing
        run: docker network create zap-net

      - name: Build app Docker image
        run: docker build -t my-app-test .

      - name: Run app container on zap-net network
        run: docker run -d --rm --name test-app --network zap-net -p 3000:3000 my-app-test

      - name: Run OWASP ZAP baseline scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://test-app:3000'
          fail_action: true
          # IMPORTANT: Specify the Docker network for the ZAP container to join
          docker_network: zap-net 

      - name: Cleanup app container and network
        if: always()
        run: |
          docker rm -f test-app || true
          docker network rm zap-net || true

      - name: Run Trivy Dependency Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          severity: 'CRITICAL,HIGH,MEDIUM,LOW'
          format: 'table'
          exit-code: '1'

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten
          error: true

  test:
    name: Run Tests
    needs: security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Cloud Run
    needs: test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/556268819010/locations/global/workloadIdentityPools/ghpool/providers/github-provider'
          service_account: 'gha-cloudrun-deployer@iapvm123.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'iapvm123'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-cloud-run-service \
            --image us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
