name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: iapvm123
  GKE_CLUSTER: cluster
  GKE_ZONE: us-central1-a
  REPOSITORY_NAME: repo
  FRONTEND_IMAGE: frontend
  BACKEND_IMAGE: node
  K8S_NAMESPACE: default

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: 'Set up Gcloud CLI'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/556268819010/locations/global/workloadIdentityPools/ghpool/providers/github-provider'
          service_account: 'gha-cloudrun-deployer@iapvm123.iam.gserviceaccount.com'

      - name: 'Configure Docker'
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Frontend Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.FRONTEND_IMAGE }}:latest ./frontend
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.FRONTEND_IMAGE }}:latest

      - name: Build and Push Backend Image
        run: |
          docker build -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.BACKEND_IMAGE }}:latest ./backend
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.BACKEND_IMAGE }}:latest

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: 'Deploy to GKE'
        run: |
          kubectl apply -f k8s/