name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]  

jobs:
  security:
    name: Security Scan (OWASP Dependency-Check & Semgrep)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install --legacy-peer-deps # Use --legacy-peer-deps to avoid potential npm install issues with older dependencies
        # This will install lodash@4.17.11 and update package-lock.json

      # --- OWASP Dependency-Check Scan (runs first) ---
      - name: Run OWASP Dependency-Check Scan
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: 'my-nodejs-app'
          path: '.' # Scan the current directory
          format: 'JSON' # Specify JSON format to avoid HTML report generation by default
          args: > # Use multi-line string for args
            --enableNodeJS # Explicitly enable the Node.js analyzer
            --disableNodeAudit # Disable the Node Audit Analyzer if it's causing issues with aliases
            --failOnCVSS 0 # Fail on any CVSS score (0 to 10), ensuring it breaks for any vuln
            --scan package-lock.json # Explicitly tell it to scan the package-lock.json
            --prettyPrint # Make JSON output more readable in logs (optional)
            --debug # Keep debug logging for more insights
      # --- End OWASP Dependency-Check Scan ---

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten  
          error: true              

  test:
    name: Run Tests
    needs: security  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Cloud Run
    needs: test  
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/556268819010/locations/global/workloadIdentityPools/ghpool/providers/github-provider'
          service_account: 'gha-cloudrun-deployer@iapvm123.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'iapvm123'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-cloud-run-service \
            --image us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated