name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]  

jobs:
  security:
    name: Security Scan (Trivy SCA & Semgrep) # Updated job name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install # This will ensure package-lock.json is up-to-date with lodash@4.17.11

      # --- NEW: Trivy SCA Scan ---
      - name: Run Trivy Dependency Scan
        uses: aquasecurity/trivy-action@master # Using the official Trivy GitHub Action
        with:
          # Trivy will automatically detect and scan package-lock.json for Node.js dependencies
          scan-type: 'fs' # Scan the file system (your repository)
          severity: 'CRITICAL,HIGH,MEDIUM,LOW' # Report vulnerabilities of all severities
          # Trivy will fail the action by default if vulnerabilities are found.
          # No API key is needed for this basic dependency scanning.
          format: 'table' # Output format directly to the console for easy viewing
          exit-code: '1' # Ensure the job fails if any vulnerability is found
          # debug: true # Uncomment for verbose logging if needed
      # --- END NEW ---

      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/owasp-top-ten  
          error: true              

  test:
    name: Run Tests
    needs: security  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy:
    name: Deploy to Cloud Run
    needs: test  
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/556268819010/locations/global/workloadIdentityPools/ghpool/providers/github-provider'
          service_account: 'gha-cloudrun-deployer@iapvm123.iam.gserviceaccount.com'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: 'iapvm123'

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy my-cloud-run-service \
            --image us-central1-docker.pkg.dev/iapvm123/repo/my-app:$GITHUB_SHA \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated